### ISSUE TITLE
Distributed Index test scenarios for 1.2

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/sync-gateway-tests#35]
## Topologies

CB            SG      Role
4 (3.1.0)   1 (1.2) [RW]  
4 (3.1.0)   4 (1.2) [RW, RW, RW, RW]
4 (3.1.0)   4 (1.2) [W, W, R, R]

4 (3.1.1)   1 (1.2) [RW]  
4 (3.1.1)   4 (1.2) [RW, RW, RW, RW]
4 (3.1.1)   4 (1.2) [W, W, R, R]

4 (4.0.0)   1 (1.2) [RW]  
4 (4.0.0)   4 (1.2) [RW, RW, RW, RW]
4 (4.0.0)   4 (1.2) [W, W, R, R]
## Scenarios

All scenarios will be run against multiple topologies
All scenarios should exercise multiple feed types (possibly)
All scenarios should be run at multiple data scales (1K docs, 10K, 100K)
All scenarios should be run with multiple user scales (10 users, 1000 users, 10000 users, per test basis)
- [x]  Single user / single channels - Unique docs with unique keys, (add)
- [x]  Single user / single channels - Unique docs with unique keys, (update)
- [x]  Single user / muliple channels - Unique docs with unique keys, (add)
- [x]  Single user / multiple channels - Unique docs with unique keys, (update)
- [x]  Muliple users / single channel - Unique docs with unique keys, (add)
- [ ]  Muliple users / single channel - Unique docs with unique keys, (update)
- [x]  Muliple users / multiple channels - Unique docs with unique keys, (add)
- [x]  Muliple users / multiple channels - Unique docs with unique keys, (update)
- [x]  Reshard of DCP - Continuous write to a vBucket range, kill sync_gateway responsible for writing those vBuckets - Unique docs with unique keys
- [ ]  sgs: Adding / Removing nodes from cluster (validate post state change). 
  Using cbgt rest api (shards to each node)
  Ensure data integrity
  Verification that all writers register with CBGT
  Bring a new writer online during continuous writes
  All sync_gateways writers go down during write for a period of time, bring them back up.
- [ ]  Channel Index Bucket Failover - Continuous doc writes with unique keys. Take down a couchbase server instance and verify that the channel index is intact after failing over to another couchbase node.
- [ ]  Remove / Add channels to documents
- [ ]  Remove / Add channels to users
  REST API calls
  Access grant in sync function
  Important to test: Newly granted access, make sure backfill occurs
  Make sure backfill only happens once (no doc dupes, ...)
- [ ] Exercise changes feed types (normal, continuous, longpoll) - perhaps in each of the above test cases.
- [ ] Multiple databases with distributed index in same bucket
- [ ] Multiple databases with distributed index in different buckets, test failover to single node
  4 sgs: each db has separate index bucket
  sg online / offline
  drop index bucket
  if the channel index bucket goes, sg should go to offline state
- [x] Different sync functions (any ideas?)
  Access calls (adding / removing users)
  Channel calls
  Role based access calls
  Exercising views - Access calls in sync function, uses a view, make sure access grants in sync function
- [ ] Adding non-winning revisions 
  Create revs further back in the tree
  Pass criteria: different sequence, same rev id = winning rev id
- [ ] Hotspot key design, index handles the case where one is slammed while other , bunch of of revs on one doc
- [x] View query scenarios?
  Access calls in sync function, uses a view, make sure access grants in sync function
- [x] Multiple writers with different shard values. 
- [ ] Flush channel index bucket should take sync_gateway offline
  Large number of docs (1,000,000). Flush index bucket to start from 0. Make sure doesn’t kill your sg writers

**Comment by ashvindersingh** [comment]
Adding the spreadsheet with more detailed info.
https://docs.google.com/spreadsheets/d/1nlba3SsWagDrnAep3rDZHXHIDmRH_FFDeTaYJms_55k/edit#gid=598127796

**Comment by ashvindersingh** [comment]
Moved the spreadsheet from personal to couchbase google apps account:
https://docs.google.com/spreadsheets/d/1pg0xg2ADYBwudQY3AOclHc78SRrQuw9ieEbrPTfTvkA/edit#gid=0

Please use this link for all the future updates and references.

**Comment by sethrosetter** [comment]
Closing this. Now tracking here https://github.com/couchbaselabs/sync-gateway-testcluster/issues/105
